tunnel: 4a638fa7-cbe1-453c-b360-95c56d17eaca
credentials-file: /home/thomas/.cloudflared/4a638fa7-cbe1-453c-b360-95c56d17eaca.json
origincert: /home/thomas/.cloudflared/cert.pem
protocol: http2

originRequest:
  connectTimeout: 30s
  noTLSVerify: false

ingress:
  - hostname: bom.best
    service: http://localhost:5002
    originRequest:
      connectTimeout: 30s
      httpHostHeader: bom.best
  - service: http_status:404
